
[cn]
start = "Hi! replace ~ 欢迎使用 iCopy" #replace==待替换占位符
guide_to_menu = "请输入 '/menu' 选择模式"
menu_msg = "请选择模式"
quick_mode = "极速模式"
copy_mode = "自定义模式"
size_mode = "文件统计"
purge_mode = "回收站清理"
dedupe_mode = "文件去重"
mode_select_msg = "本次任务您选择了 ┋replace┋" #replace==待替换占位符
request_share_link = "请输入 Google Drive 分享链接 或 分享ID"
request_dst_target = "请选择文件保存位置"
is_cover = "覆盖"
not_cover = "返回"
is_cover_quick_msg = "QUICK\\_MODE 已存在指定快捷路径\n是否需要覆盖"
insert_quick_success = "QUICK\\_MODE 指定快捷路径已设置成功"
modify_quick_success = "QUICK\\_MODE 指定快捷路径已更新成功"
null_fav_quick = "未设置QUICK\\_MODE 转存目录\n请设置后再次尝试"
null_fav = "未设置COPY\\_MODE 转存目录\n请设置后再次尝试"
ready_to_task = "转存任务准备中..."
doing = "正在执行任务"
done = "任务成功"
killed = "任务终止"
current_task_id = "任务编号 : "
task_start_time = "任务开始时间 : "
task_finished_time = "任务结束时间 : "
task_files_size = "文件总大小 : "
task_files_num = "任务文件数 : "
task_status = "任务状态 : "
elapsed_time = "总耗时 : "
cancel_msg = "欢迎再次使用 iCopy"
get_quick_count_invaild = "quick 模式下的快捷目录只允许存在一个"
get_multi_fav_error = "请根据'/set'规则提交目录设置"
get_single_fav_error = "请根据'/set rule'规则发送命令"
get_multi_in_single = "多行设置请使用 '/set'"
task_src_info = "[任务目标]:"
task_dst_info = "[转存地址]:"
is_set_dedupe = "设置收藏夹遇到错误"
set_fav_success = "设置收藏夹成功"
delete_fav_success = "删除收藏夹成功"
delete_quick_success = "QUICK_MODE 指定快捷路径已删除"
show_fav_list = "下列为已设置的收藏夹"
show_fav_list_null = "未设置任何收藏夹"
is_restarting = "iCopy机器人正在重启...\n请在30秒后开始使用"
is_killed_by_user = "任务已被用户终止"
is_current_task = "当前任务 : \n\n"
current_task_src_name = "源文件 : "
current_task_dst_name = "目标地 : "
is_not_current_task = "当前没有任务"
show_wait_list = "个任务正在队列中\n\n"
show_wait_list_null = "等待队列为空"
interrupted = "任务中断"
is_interrupted_error = "任务意外中断"
restart_success = "iCopy 重启完成"
add_task_successful = "添加任务成功"
purge_fav = "清空收藏夹 (不包含 quick目录)"
reset_successful = "任务 ID : replace 已被成功重置" #replace==待替换占位符
over_limit_error = "超出最大可重置任务序号"
over_limit_to_check = "超出最大可查询任务序号"
over_limit_to_dedupe = "超出最大可去重任务序号"
global_command_error = "输入的命令或者命令格式不存在"
ready_to_size = "正在准备统计"
sizing = "正在统计中，请耐心等待\n如果同时存在复制任务，则会影响复制与统计双方的准确性"
total_file_num = "总文件数 : "
total_file_size = "总大小 : "
sizing_done = "统计完成"
task_is_in_queue = "任务正在队列中"
finished_could_be_check = "只能查询已完成的任务"
finished_could_be_dedupe = "只能对已完成的任务进行去重"
support_error = "指定的任务不支持查询"
request_target_folder = "请选择目标收藏夹"
ready_to_purge = "正在准备清空回收站"
purging = "正在清空回收站，请耐心等待\n如果同时存在复制任务，则会影响复制与清空回收站双方的准确性"
purging_done = "已清空回收站"
request_dedupe_mode = "请选择去重模式 规则"
ready_to_dedupe = "正在准备文件去重"
deduping = "正在执行去重文件，请耐心等待\n如果同时存在复制任务，则会影响复制与文件去重双方的准确性"
deduping_done = "文件去重已完成"
is_folder_not_drive = "被选择的收藏夹是一个'文件夹'不是'团队盘'\n无法清空回收站"

[eng]
start = "Hi! replace . Welcome to use iCopy" #replace==symbolic placeholder
guide_to_menu = "Please Input '/menu' to Choose run mode"
menu_msg = "Pls Choose the Mode"
quick_mode = "QUICK MODE"
copy_mode = "COPY MODE"
size_mode = "Size"
purge_mode = "Empty Recycle bin"
dedupe_mode = "dedupe mode"
mode_select_msg = "┋replace┋ has be choosen" #replace==symbolic placeholder
request_share_link = "Pls input Shared_Link or Shared_ID"
request_dst_target = "Please select the destination path for the task"
is_cover = "Cover it"
not_cover = "Cancel"
is_cover_quick_msg = "QUICK\\_MODE The specified directory already exists\nDo you need to cover it?"
insert_quick_success = "QUICK\\_MODE specified path is setted successfully"
modify_quick_success = "QUICK\\_MODE specified path is renewed successfully"
null_fav_quick = "QUICK\\_MODE directory is not set\nPlease try again after setting"
null_fav = "COPY\\_MODE directory is not set\nPlease try again after setting"
ready_to_task = "Now is Ready to Task..."
doing = "Transferring"
done = "Done"
killed = "Killed"
current_task_id = "task id : "
task_start_time = "Task start time : "
task_finished_time = "Task end time : "
task_files_size = "Total file size : "
task_files_num = "Task file num : "
task_status = "task_status : "
elapsed_time = "Elapsed Time : "
cancel_msg = "Welcome to enjoy with iCopy again"
get_quick_count_invaild = "Only ONE Dst ID can be specified under quick mode"
get_multi_fav_error = "pls submit DST ID according '/set'"
get_single_fav_error = "pls submit single DST ID according '/set rule'"
get_multi_in_single = "pls use '/set' while modify multi DST IDs"
task_src_info = "[Resource From]:"
task_dst_info = "[Transfer To]:"
is_set_err = "SET FAV ERROR"
set_fav_success = "set Favorites success"
delete_fav_success = "Favorites deleted successfully"
delete_quick_success = "QUICK\\_MODE specified path is deleted successfully"
show_fav_list = "The following are favorites that have been set"
show_fav_list_null = "Favorites are not set"
is_restarting = "iCopy is restarting...\nPlease start using in 30 seconds"
is_killed_by_user = "Task is killed by user"
is_current_task = "Current Task : \n\n"
current_task_src_name = "Source : "
current_task_dst_name = "Destination : "
is_not_current_task = "No Task is in Processing"
show_wait_list = "task in the queue\n\n"
show_wait_list_null = "There is no task in waiting"
interrupted = "Interrupted"
is_interrupted_error = "Unexpected interruption"
restart_success = "iCopy restart is complete"
add_task_successful = "Add Task Successful"
purge_fav = "purge Favorites (except Quick path)"
reset_successful = "Task ID: replace has been reset successfully" #replace==symbolic placeholder
over_limit_error = "Exceeded maximum resettable task number"
over_limit_to_check = "Exceeded maximum task number which could be check"
over_limit_to_dedupe = "Exceeded maximum task number which could be dedupe"
global_command_error = "The input command or command format does not exist"
ready_to_size = "Preparing statistics"
sizing = "In statistics, pls wait \nIf there is a copy task, it will affect the accuracy of both copy and statistics"
total_file_num = "Total Files : "
total_file_size = "Total Size : "
sizing_done = "Size Finished"
task_is_in_queue = "Task is in the queue"
finished_could_be_check = "You could only check the task which is finished"
finished_could_be_dedupe = "You could only dedupe the task which is finished"
support_error = "The specified task does not support queries"
request_target_folder = "Pls choose the TARGET drive or folder"
ready_to_purge = "Ready to Purge"
purging = "In empty recycle bin, pls wait \nIf there is a copy task, it will affect the accuracy of both copy and recyle bin empting"
purging_done = "The recycle bin has been emptied"
request_dedupe_mode = "Please select to dedupe mode rule"
ready_to_dedupe = "Ready to dedupe"
deduping = "In deduping task, pls wait \nIf there is a copy task, it will affect the accuracy of both copy and dedupe"
deduping_done = "The task is be deduped"
is_folder_not_drive = "The selected favorites is a 'folder' not a 'shared drive'\n Can not be purged"

[jp]
start = "Hi! replace . iCopyへようこそ" #replace==置き換え指示記号
guide_to_menu = "実行モードを選択するには、'/menu' を入力してください"
menu_msg = "ご覧のモードを選んでください"
quick_mode = "「クイック」"
copy_mode = "「カスタマイズ」"
size_mode = "「サイズ」"
purge_mode = "「ごみ箱を空にする」"
dedupe_mode = "「重複を取り除く」"
mode_select_msg = "┋replace┋が選択されました" #replace==置き換え指示記号
request_share_link = "共有リンクまたは共有IDを入力してください"
request_dst_target = "ファイルの保存場所を選択してください"
is_cover = "カバー"
not_cover = "キャンセル"
is_cover_quick_msg = "QUICK_MODE指定されたフォルダーはすでに存在します\n新しいフォルダで上書きしますか?"
insert_quick_success = "QUICK_MODEで指定されたフォルダーが正常に設定されました"
modify_quick_success = "QUICK_MODEで指定されたフォルダーが更新されました"
null_fav_quick = "QUICK\\_MODEフォルダーが設定されていません\n設定後にもう一度お試しください"
null_fav = "COPY\\_MODEフォルダーが設定されていません\n設定後にもう一度お試しください"
ready_to_task = "任務準備中..."
doing = "タスク実行中"
done = "任務成功"
killed = "任務中止"
current_task_id = "タスク番号 : "
task_start_time = "タスク開始時刻 : "
task_finished_time = "タスク終了時間 : "
task_files_size = "ファイルサイズ : "
task_files_num = "タスクファイル数 : "
task_status = "タスク状態 : "
elapsed_time = "合計時間 : "
cancel_msg = "再びiCopyへようこそ"
get_quick_count_invaild = "「クイックモード」で一つフォルダーしか指定されることができない"
get_multi_fav_error = "'/set'にルールをよって、フォルダーのIDを入力してください"
get_single_fav_error = "'/set rule'にルールをよって、フォルダーのIDを入力してください"
get_multi_in_single = "複数のフォルダーを設定する場合は、「/set」コマンドを使用してください"
task_src_info = "[任務目標]:"
task_dst_info = "[保存場所]:"
is_set_dedupe = "お気に入りを設定するとエラーが発生します"
set_fav_success = "お気に入りを設定しました"
delete_fav_success = "お気に入り削除に成功"
delete_quick_success = "QUICK_MODEで指定されたフォルダーが削除されました"
show_fav_list = "以下は既設のお気に入りである"
show_fav_list_null = "お気に入りは設定いない"
is_restarting = "iCopyが再起動しています...\n30秒後に使用を開始してください"
is_killed_by_user = "タスクはユーザによって終了される"
is_current_task = "進行中のタスク : \n\n"
current_task_src_name = "源フォルダー : "
current_task_dst_name = "目標フォルダー : "
is_not_current_task = "進行中のタスクがない"
show_wait_list = "タスクが待機しています\n\n"
show_wait_list_null = "待機中のタスクはありません"
interrupted = "タスク中断"
is_interrupted_error = "予期しない中断"
restart_success = "iCopyの再開が完了する"
add_task_successful = "タスク追加成功"
purge_fav = "お気に入りをクリア（クイックフォルダーを除く）"
reset_successful = "タスク ID: replace がリセットされた"#replace==置き換え指示記号
over_limit_error = "最大リセット可能タスク番号を超える"
over_limit_to_check = "最大チェック可能タスク番号を超える"
over_limit_to_dedupe = "最大重複除外可能タスク番号を超える"
global_command_error = "入力するコマンドやコマンドフォーマットは存在しない"
ready_to_size = "統計を準備している"
sizing = "統計中ですので、お待ちください\nコピータスクが同時に存在する場合,コピーと統計の双方の正確さに影響する"
total_file_num = "総 ファイル 数 : "
total_file_size = "総 サイズ : "
sizing_done = "統計終了"
task_is_in_queue = "タスクが列に並んでいる"
finished_could_be_check = "既に完了した任務しか調べられない"
finished_could_be_dedupe = "すでに完了したタスクのみが重複ファイルの除去を行うことができる"
support_error = "指定の任務の照会を支持しない"
request_target_folder = "目標フォルダーを選んでください"
ready_to_purge = "ごみ箱を空にする準備をしています"
purging = "ごみ箱をクリアしています。\n同時にコピーの任務がある場合、コピーとごみ箱を空にすることの両方の正確さに影響します"
purging_done = "既にごみ箱を空にした"
request_dedupe_mode = "重複除外モードのルールを選択してください"
ready_to_dedupe = "重複ファイルを除去する準備をしています"
deduping = "重複ファイルを除去しています。\n同時にコピーの任務がある場合、コピーと重複除外の両方の正確さに影響します"
deduping_done = "重複ファイルの除去が完了しました"
is_folder_not_drive = "選択されたお気に入りは「フォルダ」ではなく「シェアドライバ」で\nゴミ箱を空にできない"