
[cn]
start = "Hi! replace ~ 欢迎使用 iCopy" #replace==待替换占位符
guide_to_menu = "请输入 '/menu' 选择模式"
menu_msg = "请选择转存模式"
quick_mode = "极速模式"
copy_mode = "自定义模式"
mode_select_msg = "本次转存任务您选择了 ┋replace┋" #replace==待替换占位符
request_share_link = "请输入 Google Drive 分享链接 或 分享ID"
request_dst_target = "请选择文件保存位置"
is_cover = "覆盖"
not_cover = "返回"
is_cover_quick_msg = "QUICK\\_MODE 已存在指定快捷路径\n是否需要覆盖"
insert_quick_success = "QUICK\\_MODE 指定快捷路径已设置成功"
modify_quick_success = "QUICK\\_MODE 指定快捷路径已更新成功"
null_fav_quick = "未设置QUICK\\_MODE 转存目录\n请设置后再次尝试"
null_fav = "未设置COPY\\_MODE 转存目录\n请设置后再次尝试"
ready_to_task = "转存任务准备中..."
doing = "正在执行任务"
done = "任务成功"
killed = "任务终止"
current_task_id = "任务编号 : "
task_start_time = "任务开始时间 : "
task_finished_time = "任务结束时间 : "
task_files_size = "文件总大小 : "
task_files_num = "任务文件数 : "
task_status = "任务状态:"
elapsed_time = "总耗时 : "
cancel_msg = "欢迎再次使用 iCopy"
get_quick_count_invaild = "quick 模式下的快捷目录只允许存在一个"
get_multi_fav_error = "请根据'/set'规则提交目录设置"
get_single_fav_error = "请根据'/set rule'规则发送命令"
get_multi_in_single = "多行设置请使用 '/set'"
task_src_info = "[任务目标]:"
task_dst_info = "[转存地址]:"
is_set_dedupe = "设置收藏夹遇到错误"
set_fav_success = "设置收藏夹成功"
delete_fav_success = "删除收藏夹成功"
delete_quick_success = "QUICK_MODE 指定快捷路径已删除"
show_fav_list = "下列为已设置的收藏夹"
show_fav_list_null = "未设置任何收藏夹"
is_restarting = "iCopy机器人正在重启...\n请在30秒后开始使用"
is_killed_by_user = "任务已被用户终止"
is_current_task = "当前任务 : \n\n"
current_task_src_name = "源文件 : "
current_task_dst_name = "目标地 : "
is_not_current_task = "当前没有任务"
show_wait_list = "个任务正在队列中"
show_wait_list_null = "等待队列为空"
interrupted = "任务中断"
is_interrupted_error = "任务意外中断"
restart_success = "iCopy 重启完成"
add_task_successful = "添加任务成功"
purge_fav = "清空收藏夹 (不包含 quick目录)"
reset_successful = "任务 ID : replace 已被成功重置" #replace==待替换占位符
over_limit_error = "超出最大可重置任务序号"
global_command_error = "输入的命令或者命令格式不存在"
ready_to_size = "正在准备统计"
sizing = "正在统计中，请耐心等待\n如果同时存在复制任务，则会影响复制与统计双方的准确性"
total_file_num = "总文件数 : "
total_file_size = "总大小 : "
sizing_done = "统计完成"

[eng]
start = "Hi! replace . Welcome to use iCopy" #replace==symbolic placeholder
guide_to_menu = "Please Input '/menu' to Choose run mode"
menu_msg = "Pls Choose the Transfer Mode"
quick_mode = "QUICK MODE"
copy_mode = "COPY MODE"
mode_select_msg = "┋replace┋ has be choosen" #replace==symbolic placeholder
request_share_link = "Pls input Shared_Link or Shared_ID"
request_dst_target = "Please select the destination path for the task"
is_cover = "Cover it"
not_cover = "Cancel"
is_cover_quick_msg = "QUICK\\_MODE The specified directory already exists\nDo you need to cover it?"
insert_quick_success = "QUICK\\_MODE specified path is setted successfully"
modify_quick_success = "QUICK\\_MODE specified path is renewed successfully"
null_fav_quick = "QUICK\\_MODE directory is not set\nPlease try again after setting"
null_fav = "COPY\\_MODE directory is not set\nPlease try again after setting"
ready_to_task = "Now is Ready to Task..."
doing = "Transferring"
done = "Done"
killed = "Killed"
current_task_id = "task id : "
task_start_time = "Task start time : "
task_finished_time = "Task end time : "
task_files_size = "Total file size : "
task_files_num = "Task file num : "
task_status = "task_status:"
elapsed_time = "Elapsed Time : "
cancel_msg = "Welcome to enjoy with iCopy again"
get_quick_count_invaild = "Only ONE Dst ID can be specified under quick mode"
get_multi_fav_error = "pls submit DST ID according '/set'"
get_single_fav_error = "pls submit single DST ID according '/set rule'"
get_multi_in_single = "pls use '/set' while modify multi DST IDs"
task_src_info = "[Resource From]:"
task_dst_info = "[Transfer To]:"
is_set_err = "SET FAV ERROR"
set_fav_success = "set Favorites success"
delete_fav_success = "Favorites deleted successfully"
delete_quick_success = "QUICK\\_MODE specified path is deleted successfully"
show_fav_list = "The following are favorites that have been set"
show_fav_list_null = "Favorites are not set"
is_restarting = "iCopy is restarting...\nPlease start using in 30 seconds"
is_killed_by_user = "Task is killed by user"
is_current_task = "Current Task : \n\n"
current_task_src_name = "Source : "
current_task_dst_name = "Destination : "
is_not_current_task = "No Task is in Processing"
show_wait_list = "task in the queue"
show_wait_list_null = "There is no task in waiting"
interrupted = "Interrupted"
is_interrupted_error = "Unexpected interruption"
restart_success = "iCopy restart is complete"
add_task_successful = "Add Task Successful"
purge_fav = "purge Favorites (except Quick path)"
reset_successful = "Task ID: replace has been reset successfully" #replace==symbolic placeholder
over_limit_error = "Exceeded maximum resettable task number"
global_command_error = "The input command or command format does not exist"
ready_to_size = "Preparing statistics"
sizing = "In statistics, pls wait \nIf there is a copy task, it will affect the accuracy of both copy and statistics"
total_file_num = "Total Files : "
total_file_size = "Total Size : "
sizing_done = "Size Finished"

[jp]
start = "Hi! replace . iCopyへようこそ" #replace==置き換え指示記号
guide_to_menu = "実行モードを選択するには、'/menu' を入力してください"
menu_msg = "ご覧のモードを選んでください"
quick_mode = "「クイックモード」"
copy_mode = "「カスタマイズ　モード」"
mode_select_msg = "┋replace┋が選択されました" #replace==置き換え指示記号
request_share_link = "共有リンクまたは共有IDを入力してください"
request_dst_target = "ファイルの保存場所を選択してください"
is_cover = "カバー"
not_cover = "キャンセル"
is_cover_quick_msg = "QUICK_MODE指定されたフォルダーはすでに存在します\n新しいフォルダで上書きしますか?"
insert_quick_success = "QUICK_MODEで指定されたフォルダーが正常に設定されました"
modify_quick_success = "QUICK_MODEで指定されたフォルダーが更新されました"
null_fav_quick = "QUICK\\_MODEフォルダーが設定されていません\n設定後にもう一度お試しください"
null_fav = "COPY\\_MODEフォルダーが設定されていません\n設定後にもう一度お試しください"
ready_to_task = "任務準備中..."
doing = "タスク実行中"
done = "任務成功"
killed = "任務中止"
current_task_id = "タスク番号 : "
task_start_time = "タスク開始時刻 : "
task_finished_time = "タスク終了時間 : "
task_files_size = "ファイルサイズ : "
task_files_num = "タスクファイル数 : "
task_status = "タスク状態:"
elapsed_time = "合計時間 : "
cancel_msg = "再びiCopyへようこそ"
get_quick_count_invaild = "「クイックモード」で一つフォルダーしか指定されることができない"
get_multi_fav_error = "'/set'にルールをよって、フォルダーのIDを入力してください"
get_single_fav_error = "'/set rule'にルールをよって、フォルダーのIDを入力してください"
get_multi_in_single = "複数のフォルダーを設定する場合は、「/set」コマンドを使用してください"
task_src_info = "[任務目標]:"
task_dst_info = "[保存場所]:"
is_set_dedupe = "お気に入りを設定するとエラーが発生します"
set_fav_success = "お気に入りを設定しました"
delete_fav_success = "お気に入り削除に成功"
delete_quick_success = "QUICK_MODEで指定されたフォルダーが削除されました"
show_fav_list = "以下は既設のお気に入りである"
show_fav_list_null = "お気に入りは設定いない"
is_restarting = "iCopyが再起動しています...\n30秒後に使用を開始してください"
is_killed_by_user = "タスクはユーザによって終了される"
is_current_task = "進行中のタスク : \n\n"
current_task_src_name = "源フォルダー : "
current_task_dst_name = "目標フォルダー : "
is_not_current_task = "進行中のタスクがない"
show_wait_list = "タスクが待機しています"
show_wait_list_null = "待機中のタスクはありません"
interrupted = "タスク中断"
is_interrupted_error = "予期しない中断"
restart_success = "iCopyの再開が完了する"
add_task_successful = "タスク追加成功"
purge_fav = "お気に入りをクリア（クイックフォルダーを除く）"
reset_successful = "タスク ID: replace がリセットされた"#replace==置き換え指示記号
over_limit_error = "最大リセット可能タスク番号を超える"
global_command_error = "入力するコマンドやコマンドフォーマットは存在しない"
ready_to_size = "統計を準備している"
sizing = "統計中ですので、お待ちください\nコピータスクが同時に存在する場合,コピーと統計の双方の正確さに影響する"
total_file_num = "総 ファイル 数 : "
total_file_size = "総 サイズ : "
sizing_done = "統計終了"